Repository nodekraft/nodekraft-core-api, pull requests merged in 2020-11, with the labels that each got.

#7 Create dependabot.yml
  .github/dependabot.yml
Labels: automation

#8 Fixed image issue in README
  README.md
  assets/images/nodekraft.png
  docs/LICENSE
  docs/folder-structure.md
  package-lock.json
  package.json
  src/api/records.js
  src/app.js
Labels: documentation

#9 Update git ignore
  .DS_Store
  .gitignore
Labels: enhancement
