Repository nodekraft/nodekraft-core-api, pull requests merged in 2020-12, with the labels that each got.

#10 Feature database integration
  .DS_Store
  package-lock.json
  package.json
  src/database/.dump/DevelopmentResources.sql
  src/database/development.db
  src/database/development.sql
  src/database/development.sql.sqbpro
Labels: Workshop, enhancement

#11 Delete .DS_Store
  .DS_Store
Labels: enhancement

#13 Create security policy .md file
  SECURITY.md
Labels: documentation, feature, security

#12 Security sweeper
  .github/workflows/codeql-analysis.yml
Labels: automation, enhancement, feature, security
